#!/bin/bash

# Deps:
# 	curl


get_weather()
{
	curl -s v2.wttr.in | grep -e "Weather" | sed -n 2p | sed s/Weather://g | sed 's/,//g' | sed 's/+//g' | sed 's/°C.*/°C/' | sed 's/.*m//'
}


if [ $(( 30#$(date '+%S') % 30 )) -eq 0 ]; then
    sleep 1s;
	get_weather
fi

get_weather
