#!/bin/bash

# What modules, in what order
MODULES="mpd weather date time"

# Modules that require an active internet connection
ONLINE_MODULES="weather"

# Delay between showing the status bar
DELAY="0.50"

# Where the custom modules are stored
CUSTOM_DIR="/home/$USER/.config/dwmbar/modules/custom/"

# Separator between modules
SEPARATOR=" | "

# Padding at the end and beginning of the status bar
RIGHT_PADDING=" "
LEFT_PADDING=" "
